<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->

In [1]:
#|output: asis
#| echo: false
show_doc(arr_to_dict)

D:\Programmeren\adventofcode\.aocenv\lib\site-packages\fastcore\docscrape.py:225: UserWarning: potentially wrong underline length... 
Example 
-------- in 
Example
--------...
  else: warn(msg)
D:\Programmeren\adventofcode\.aocenv\lib\site-packages\fastcore\docscrape.py:225: UserWarning: Unknown section Example
  else: warn(msg)


---

[source](https://github.com/jvanelteren/aocutils/blob/master/aocutils/grid.py#L12){target="_blank" style="float:right; font-size:smaller"}

### arr_to_dict

>      arr_to_dict (arr)

|    | **Type** | **Details** |
| -- | -------- | ----------- |
| arr |  |  |
| **Returns** | **dict** | **numpy array or list of lists (tuple of tuples)** |

In [ ]:
assert arr_to_dict([[1,2,3]]) == {(0, 0): 1, (0, 1): 2, (0, 2): 3}
assert arr_to_dict([[1,2], [3,4]]) == {(0, 0): 1, (0, 1): 2, (1, 0): 3, (1, 1): 4}
assert arr_to_dict(((1,2), (3,4))) == {(0, 0): 1, (0, 1): 2, (1, 0): 3, (1, 1): 4}
assert arr_to_dict([['a','b'],['c','#']]) == {(0, 0): 'a', (0, 1): 'b', (1, 0): 'c', (1, 1): '#'}

In [3]:
#|output: asis
#| echo: false
show_doc(grid_to_dict)

---

[source](https://github.com/jvanelteren/aocutils/blob/master/aocutils/grid.py#L29){target="_blank" style="float:right; font-size:smaller"}

### grid_to_dict

>      grid_to_dict (grid)

In [ ]:
assert grid_to_dict([[1,2,3],[4,5,6]]) == {(0, 0): 1, (0, 1): 2, (0, 2): 3, (1, 0): 4, (1, 1): 5, (1, 2): 6}
assert grid_to_dict('1r3\n456') == {(0, 0): '1', (0, 1): 'r', (0, 2): '3', (1, 0): '4', (1, 1): '5', (1, 2): '6'}

In [4]:
#|output: asis
#| echo: false
show_doc(neighbors)

---

[source](https://github.com/jvanelteren/aocutils/blob/master/aocutils/grid.py#L37){target="_blank" style="float:right; font-size:smaller"}

### neighbors

>      neighbors (i, diag=False, inc_self=False)

determine the neighbors, returns a set with neighboring tuples {(0,1)}
if inc_self: returns self in results
if diag: return diagonal moves as well

In [ ]:
# 4 and 5 tuples
assert neighbors((0,0), inc_self=False, diag=False) == {(0, 1), (0, -1), (1, 0), (-1, 0)}
assert neighbors((0,0), inc_self=True, diag=False) == {(0, 1), (0, -1), (1, 0), (-1, 0), (0, 0)}
# # 8 and 9 tuples
assert neighbors((0,0), inc_self=False, diag=True) == {(-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 1), (1, -1), (1, 0), (1, 1)}
assert neighbors((0,0), inc_self=True, diag=True) == {(1, 1), (1, -1), (1, 0), (0, 1), (0, -1), (0, 0), (-1, 1), (-1, -1), (-1, 0)}

In [5]:
#|output: asis
#| echo: false
show_doc(arr_neighbors)

---

[source](https://github.com/jvanelteren/aocutils/blob/master/aocutils/grid.py#L56){target="_blank" style="float:right; font-size:smaller"}

### arr_neighbors

>      arr_neighbors (arr, diag=False, inc_self=False)

Returns a dictionary with index: set of neighbor indices
Parameters: diag to include diagonal neighbors, inc_self to include self in result list
Usage: for index, neighbor_indices in aoc.arr_neighbors(arr).items():

In [ ]:
a = np.arange(9).reshape(3,3).astype(object)
print(a)
arr_neighbors(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


{(0, 0): {(0, 1), (1, 0)},
 (0, 1): {(0, 0), (0, 2), (1, 1)},
 (0, 2): {(0, 1), (1, 2)},
 (1, 0): {(0, 0), (1, 1), (2, 0)},
 (1, 1): {(0, 1), (1, 0), (1, 2), (2, 1)},
 (1, 2): {(0, 2), (1, 1), (2, 2)},
 (2, 0): {(1, 0), (2, 1)},
 (2, 1): {(1, 1), (2, 0), (2, 2)},
 (2, 2): {(1, 2), (2, 1)}}

In [ ]:
arr_neighbors([[1,2,3],[3,4,4]])

{(0, 0): {(0, 1), (1, 0)},
 (0, 1): {(0, 0), (0, 2), (1, 1)},
 (0, 2): {(0, 1), (1, 2)},
 (1, 0): {(0, 0), (1, 1)},
 (1, 1): {(0, 1), (1, 0), (1, 2)},
 (1, 2): {(0, 2), (1, 1)}}

In [6]:
#|output: asis
#| echo: false
show_doc(iterate)

---

[source](https://github.com/jvanelteren/aocutils/blob/master/aocutils/grid.py#L72){target="_blank" style="float:right; font-size:smaller"}

### iterate

>      iterate (grid)

In [7]:
#|output: asis
#| echo: false
show_doc(dimensions)

---

[source](https://github.com/jvanelteren/aocutils/blob/master/aocutils/grid.py#L79){target="_blank" style="float:right; font-size:smaller"}

### dimensions

>      dimensions (obj, axis=0)

takes an iterable of iterables and returns a namedtuple with minima, maxima and range
for example a 2d numpy array
dim.min, dim.max and dim.range

In [ ]:
matrix = [[1,2,3],[10,9,8]]
assert dimensions(matrix) == Dim(min=(1, 2, 3), max=(10, 9, 8), range=(9, 7, 5))
assert dimensions(matrix, axis=1) == Dim(min=(1, 8), max=(3, 10), range=(2,2))
assert dimensions(np.array(matrix)) == Dim(min=(1, 2, 3), max=(10, 9, 8), range=(9, 7, 5))

In [8]:
#|output: asis
#| echo: false
show_doc(positive)

---

[source](https://github.com/jvanelteren/aocutils/blob/master/aocutils/grid.py#L96){target="_blank" style="float:right; font-size:smaller"}

### positive

>      positive (*args)

takes 1 or multiple lists of n coordinates and returns it normalized (getting rid of negatives)
Only works along rows! (axis=0)

positive() will only make changes along axis where negative values are detected

In [ ]:
assert positive([(0,0,-4),(0,-10,0),(0,0,0)]) == [(0, 10, 0), (0, 0, 4), (0, 10, 4)]

In [9]:
#|output: asis
#| echo: false
show_doc(manhattan)

---

[source](https://github.com/jvanelteren/aocutils/blob/master/aocutils/grid.py#L120){target="_blank" style="float:right; font-size:smaller"}

### manhattan

>      manhattan (a, b)

In [ ]:
assert manhattan((10,10),(-1,11)) == 12
assert manhattan((0,5),(-1,8)) == 4
assert manhattan((10,10,10),(-1,11,12)) == 14
assert manhattan((-1,-2,-3,-4),(3,6,2,-1)) == 20

In [10]:
#|output: asis
#| echo: false
show_doc(conv1d)

---

[source](https://github.com/jvanelteren/aocutils/blob/master/aocutils/grid.py#L125){target="_blank" style="float:right; font-size:smaller"}

### conv1d

>      conv1d (arr, conv_shape, mode='same', padding=None, pad_dir='center')

Returns a list of kernel views of a string or list 
mode == 'valid': returns only results where the kernel fits
mode == 'same': return the same amount of items as original
when mode =='same', default padding is the outer value

In [ ]:
conv1d("12345",3,mode='valid') == ['123', '234', '345']
conv1d("12345",3,mode='same')
# conv1d("12345",2,mode='valid') == ['123', '234', '345'])

not fully checked yet valid
not fully checked yet same


['112', '123', '234', '345', '451']

In [11]:
#|output: asis
#| echo: false
show_doc(conv2d)

---

[source](https://github.com/jvanelteren/aocutils/blob/master/aocutils/grid.py#L170){target="_blank" style="float:right; font-size:smaller"}

### conv2d

>      conv2d (arr, conv_shape, mode='valid', padding=None, pad_dir='center')

Returns a list of kernel views of a string or list 
mode == 'valid': returns only results where the kernel fits
mode == 'same': return the same amount of items as original
when mode =='same', default padding is the outer value

In [ ]:
conv2d(np.array([np.arange(9).reshape(3,3)]), conv_shape=2)

not fully checked yet


[]

In [12]:
#|output: asis
#| echo: false
show_doc(rotate)

---

[source](https://github.com/jvanelteren/aocutils/blob/master/aocutils/grid.py#L214){target="_blank" style="float:right; font-size:smaller"}

### rotate

>      rotate (locs, flip=False)

Rotates a given pattern by 90 degrees (like a puzzle piece)
when flip=True, also piece around leading to maximum of 8 options

In [ ]:
locs = [(0,0), (0,1), (0,2),(1,2)]
assert len({frozenset(s) for s in rotate(locs, flip=True)}) == 8
locs = [(0,0), (0,1)]
assert len({frozenset(s) for s in rotate(locs, flip=True)}) == 2